vim.opt.relativenumber = true
vim.opt.nu = true
vim.opt.smartindent = true
-- vim.g.mapleader = "<Space>"
vim.opt.wrap = true
vim.g.mapleader = ","
vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.clipboard = "unnamedplus"
vim.opt.backup = false
vim.opt.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.opt.undofile = true
vim.opt.updatetime = 50
-- vim.opt.guifont = "JetBrains Mono:h14"
vim.opt.guifont = "Berkeley Mono:h14"
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.termguicolors = true
